# Generated by Django 5.2.17 on 2026-09-07 07:04

import uuid

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingEvent",
            fields=[
                (
                    "event_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("fingerprint", models.CharField(max_length=71)),
                ("display_id", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=1000)),
                ("severity", models.CharField(max_length=20)),
                ("category", models.CharField(max_length=40)),
                ("verification_status", models.CharField(max_length=30)),
                ("lifecycle", models.CharField(default="open", max_length=30)),
                ("data", models.JSONField()),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "replacement_fingerprint",
                    models.CharField(blank=True, max_length=71),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("suspended", models.BooleanField(default=False)),
                ("deletion_requested_at", models.DateTimeField(blank=True, null=True)),
                ("brand_name", models.CharField(blank=True, max_length=100)),
                ("brand_color", models.CharField(default="#155eef", max_length=7)),
                ("logo_url", models.URLField(blank=True)),
                ("custom_domain", models.CharField(blank=True, max_length=253)),
                ("domain_verified_at", models.DateTimeField(blank=True, null=True)),
                ("domain_challenge", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="RateBucket",
            fields=[
                (
                    "key",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("window", models.BigIntegerField()),
                ("count", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("email_verified", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("data", models.JSONField()),
                ("lifecycle", models.CharField(max_length=30)),
                ("remediation", models.JSONField(null=True)),
                ("reconciliation", models.JSONField(null=True)),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="hubapp.finding",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hubapp.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("reviewer", "Reviewer"),
                            ("viewer", "Viewer"),
                        ],
                        default="viewer",
                        max_length=16,
                    ),
                ),
                ("billing_access", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hubapp.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JiraConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                ("base_url", models.URLField()),
                ("encrypted_token", models.TextField()),
                ("enabled", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hubapp.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JiraBinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("project_key", models.CharField(max_length=100)),
                ("issue_type", models.CharField(default="Task", max_length=100)),
                ("enabled", models.BooleanField(default=True)),
                ("resolved_transition", models.CharField(blank=True, max_length=100)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hubapp.jiraconnection",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hubapp.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JiraAssociation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("issue_id", models.CharField(max_length=100)),
                ("issue_key", models.CharField(max_length=100)),
                ("managed_comment_id", models.CharField(blank=True, max_length=100)),
                ("payload_hash", models.CharField(blank=True, max_length=64)),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hubapp.finding"
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hubapp.jiraconnection",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hubapp.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("reviewer", "Reviewer"),
                            ("viewer", "Viewer"),
                        ],
                        default="viewer",
                        max_length=16,
                    ),
                ),
                ("token_hash", models.CharField(max_length=128)),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hubapp.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="finding",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hubapp.organization"
            ),
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.CharField(blank=True, max_length=100)),
                ("action", models.CharField(max_length=100)),
                ("target", models.CharField(blank=True, max_length=200)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hubapp.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApiClient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                ("token_hash", models.CharField(max_length=128)),
                ("scopes", models.JSONField(default=list)),
                (
                    "repository_external_id",
                    models.CharField(blank=True, max_length=500),
                ),
                ("revoked_at", models.DateTimeField(null=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hubapp.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("state", models.CharField(default="pending", max_length=30)),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("completed_at", models.DateTimeField(null=True)),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hubapp.jirabinding",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hubapp.observation",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hubapp.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("outcome", models.CharField(max_length=50)),
                ("http_status", models.PositiveIntegerField(null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hubapp.organization",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hubapp.outboxevent",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("external_id", models.CharField(max_length=500)),
                ("name", models.CharField(max_length=200)),
                ("clone_url", models.CharField(blank=True, max_length=1000)),
                ("default_branch", models.CharField(default="main", max_length=200)),
                ("active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hubapp.organization",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="jirabinding",
            name="repository",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="hubapp.repository"
            ),
        ),
        migrations.AddField(
            model_name="finding",
            name="repository",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hubapp.repository"
            ),
        ),
        migrations.CreateModel(
            name="ReviewImport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("run_id", models.CharField(max_length=250)),
                ("payload_hash", models.CharField(max_length=64)),
                ("payload", models.JSONField()),
                ("payload_bytes", models.PositiveIntegerField(default=0)),
                ("source_commit", models.CharField(max_length=64)),
                ("source_branch", models.CharField(max_length=200)),
                ("mode", models.CharField(max_length=16)),
                ("result", models.JSONField(default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hubapp.organization",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hubapp.repository",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="observation",
            name="review_import",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hubapp.reviewimport"
            ),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("plan", models.CharField(default="trial", max_length=20)),
                ("status", models.CharField(default="trialing", max_length=20)),
                ("valid_until", models.DateTimeField(null=True)),
                ("grace_until", models.DateTimeField(null=True)),
                ("stripe_customer", models.CharField(blank=True, max_length=100)),
                ("stripe_subscription", models.CharField(blank=True, max_length=100)),
                ("provider_event_at", models.BigIntegerField(default=0)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hubapp.organization",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="user_email_case_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("organization", "user"), name="membership_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="jiraconnection",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="jira_tenant_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="jiraassociation",
            constraint=models.UniqueConstraint(
                fields=("finding", "connection"), name="jira_association_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="jiraassociation",
            constraint=models.UniqueConstraint(
                fields=("connection", "issue_id"), name="jira_issue_once"
            ),
        ),
        migrations.AddIndex(
            model_name="outboxevent",
            index=models.Index(
                fields=["organization", "state", "next_attempt_at"],
                name="hubapp_outb_organiz_3b7298_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="outboxevent",
            constraint=models.UniqueConstraint(
                fields=("observation", "binding"), name="delivery_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="repository",
            constraint=models.UniqueConstraint(
                fields=("organization", "external_id"),
                name="repository_tenant_identity",
            ),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["organization", "lifecycle", "severity"],
                name="hubapp_find_organiz_a4c44d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="finding",
            constraint=models.UniqueConstraint(
                fields=("repository", "fingerprint"), name="finding_identity"
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewimport",
            constraint=models.UniqueConstraint(
                fields=("repository", "run_id"), name="review_run_identity"
            ),
        ),
        migrations.AddConstraint(
            model_name="observation",
            constraint=models.UniqueConstraint(
                fields=("finding", "review_import"), name="observation_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("organization",), name="one_subscription_per_org"
            ),
        ),
    ]
