# Generated by Django 5.2.17 on 2026-09-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hubapp", "0002_tenant_guards"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("domain_verified_at__isnull", False),
                    models.Q(("custom_domain", ""), _negated=True),
                ),
                fields=("custom_domain",),
                name="verified_domain_unique",
            ),
        ),
    ]
