# Generated by Django 5.2.17 on 2026-09-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hubapp", "0003_organization_verified_domain_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="checkout_expires_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="checkout_session",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
