# Generated by Django 5.2.17 on 2026-09-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hubapp", "0004_subscription_checkout_expires_at_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("stripe_customer", ""), _negated=True),
                fields=("stripe_customer",),
                name="stripe_customer_owner_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("stripe_subscription", ""), _negated=True),
                fields=("stripe_subscription",),
                name="stripe_subscription_owner_unique",
            ),
        ),
    ]
