# Generated by Django 5.2.17 on 2026-09-08 15:20

import uuid

import django.db.models.deletion
from django.db import migrations, models


def install_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    name = "hubapp_findingactivity"
    schema_editor.execute(f"ALTER TABLE {name} ENABLE ROW LEVEL SECURITY")
    schema_editor.execute(f"ALTER TABLE {name} FORCE ROW LEVEL SECURITY")
    schema_editor.execute(
        f"CREATE POLICY tenant_isolation ON {name} USING (organization_id = NULLIF(current_setting('hub.organization_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('hub.organization_id', true), '')::uuid)"
    )
    schema_editor.execute(
        f"CREATE TRIGGER tenant_owner_guard BEFORE UPDATE ON {name} FOR EACH ROW EXECUTE FUNCTION hub_check_tenant_reference()"
    )
    for index, (field, related) in enumerate(
        (("finding_id", "hubapp_finding"), ("baseline_observation_id", "hubapp_observation"))
    ):
        schema_editor.execute(
            f"CREATE TRIGGER tenant_reference_{index} BEFORE INSERT OR UPDATE ON {name} FOR EACH ROW EXECUTE FUNCTION hub_check_tenant_reference('{field}', '{related}')"
        )


def uninstall_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        for trigger in ("tenant_owner_guard", "tenant_reference_0", "tenant_reference_1"):
            schema_editor.execute(f"DROP TRIGGER {trigger} ON hubapp_findingactivity")
        schema_editor.execute("DROP POLICY tenant_isolation ON hubapp_findingactivity")
        schema_editor.execute("ALTER TABLE hubapp_findingactivity DISABLE ROW LEVEL SECURITY")


class Migration(migrations.Migration):
    dependencies = [
        ("hubapp", "0005_subscription_stripe_customer_owner_unique_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="implementation_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="finding",
            name="implementation_revision",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="finding",
            name="implementation_text",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="FindingActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("request_id", models.UUIDField()),
                ("kind", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                ("actor", models.CharField(max_length=100)),
                ("revision", models.PositiveIntegerField()),
                ("proposal", models.TextField(blank=True)),
                ("comment", models.TextField(blank=True)),
                ("data", models.JSONField(default=dict)),
                ("payload_bytes", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(null=True)),
                (
                    "baseline_observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hubapp.observation"
                    ),
                ),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="hubapp.finding",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hubapp.organization"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "request_id"), name="finding_activity_request"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "running")),
                        fields=("finding",),
                        name="one_running_implementation",
                    ),
                ],
            },
        ),
        migrations.RunPython(install_guards, uninstall_guards),
    ]
