# Generated by Django 5.2.17 on 2026-09-09 16:27

import uuid

import django.db.models.deletion
from django.db import migrations, models


def install_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for name in ("hubapp_changerequest", "hubapp_changerequestactivity"):
        schema_editor.execute(f"ALTER TABLE {name} ENABLE ROW LEVEL SECURITY")
        schema_editor.execute(f"ALTER TABLE {name} FORCE ROW LEVEL SECURITY")
        schema_editor.execute(
            f"CREATE POLICY tenant_isolation ON {name} USING (organization_id = NULLIF(current_setting('hub.organization_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('hub.organization_id', true), '')::uuid)"
        )
        schema_editor.execute(
            f"CREATE TRIGGER tenant_owner_guard BEFORE UPDATE ON {name} FOR EACH ROW EXECUTE FUNCTION hub_check_tenant_reference()"
        )
    schema_editor.execute(
        "CREATE TRIGGER tenant_reference_0 BEFORE INSERT OR UPDATE ON hubapp_changerequestactivity FOR EACH ROW EXECUTE FUNCTION hub_check_tenant_reference('change_request_id', 'hubapp_changerequest')"
    )


def uninstall_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("DROP TRIGGER tenant_reference_0 ON hubapp_changerequestactivity")
    for name in ("hubapp_changerequest", "hubapp_changerequestactivity"):
        schema_editor.execute(f"DROP TRIGGER tenant_owner_guard ON {name}")
        schema_editor.execute(f"DROP POLICY tenant_isolation ON {name}")
        schema_editor.execute(f"ALTER TABLE {name} DISABLE ROW LEVEL SECURITY")


class Migration(migrations.Migration):
    dependencies = [
        ("hubapp", "0006_finding_implementation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("bug", "Bug fix"), ("feature", "Feature request")], max_length=10
                    ),
                ),
                ("description", models.TextField(max_length=20000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("analyzed", "Analyzed"),
                            ("specified", "Specified"),
                            ("implemented", "Implemented"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("created_by", models.CharField(max_length=254)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("payload_bytes", models.PositiveIntegerField(default=0)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hubapp.organization"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChangeRequestActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.CharField(max_length=254)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("edited", "Edited"),
                            ("transitioned", "Status changed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[("bug", "Bug fix"), ("feature", "Feature request")], max_length=10
                    ),
                ),
                ("description", models.TextField()),
                ("previous_status", models.CharField(blank=True, max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("analyzed", "Analyzed"),
                            ("specified", "Specified"),
                            ("implemented", "Implemented"),
                            ("closed", "Closed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("payload_bytes", models.PositiveIntegerField(default=0)),
                (
                    "change_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="hubapp.changerequest",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hubapp.organization"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="changerequest",
            index=models.Index(
                fields=["organization", "status", "-updated_at"],
                name="hubapp_chan_organiz_aaf5a9_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="changerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["bug", "feature"])), name="request_kind_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="changerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["open", "analyzed", "specified", "implemented", "closed"])
                ),
                name="request_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="changerequestactivity",
            constraint=models.UniqueConstraint(
                fields=("change_request", "revision"), name="request_revision_unique"
            ),
        ),
        migrations.RunPython(install_guards, uninstall_guards),
    ]
