# Generated by Django 5.2.17 on 2026-09-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hubapp", "0008_tech_lead_tokens"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="changerequest",
            name="request_status_valid",
        ),
        migrations.AddField(
            model_name="changerequest",
            name="analysis",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="changerequest",
            name="analysis_submission_digest",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="changerequest",
            name="analysis_submission_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="changerequest",
            name="repository_external_id",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="changerequestactivity",
            name="analysis",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="changerequestactivity",
            name="repository_external_id",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="changerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("analyzed", "Analyzed"),
                    ("specified", "Specified"),
                    ("implemented", "Implemented"),
                    ("closed", "Closed"),
                    ("cancelled", "Cancelled"),
                ],
                default="open",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="changerequestactivity",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("analyzed", "Analyzed"),
                    ("specified", "Specified"),
                    ("implemented", "Implemented"),
                    ("closed", "Closed"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="changerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["open", "analyzed", "specified", "implemented", "closed", "cancelled"],
                    )
                ),
                name="request_status_valid",
            ),
        ),
    ]
