# Generated by Django 5.2.17 on 2026-09-11 14:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


def install_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    table = "hubapp_requestimplementation"
    schema_editor.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
    schema_editor.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
    schema_editor.execute(
        f"CREATE POLICY tenant_isolation ON {table} USING (organization_id = NULLIF(current_setting('hub.organization_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('hub.organization_id', true), '')::uuid)"
    )
    schema_editor.execute(
        f"CREATE TRIGGER tenant_owner_guard BEFORE UPDATE ON {table} FOR EACH ROW EXECUTE FUNCTION hub_check_tenant_reference()"
    )
    schema_editor.execute(
        f"CREATE TRIGGER tenant_reference_0 BEFORE INSERT OR UPDATE ON {table} FOR EACH ROW EXECUTE FUNCTION hub_check_tenant_reference('change_request_id', 'hubapp_changerequest')"
    )


def uninstall_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("DROP TRIGGER tenant_reference_0 ON hubapp_requestimplementation")
    schema_editor.execute("DROP TRIGGER tenant_owner_guard ON hubapp_requestimplementation")
    schema_editor.execute("DROP POLICY tenant_isolation ON hubapp_requestimplementation")
    schema_editor.execute("ALTER TABLE hubapp_requestimplementation DISABLE ROW LEVEL SECURITY")


class Migration(migrations.Migration):
    dependencies = [
        ("hubapp", "0009_request_analysis"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestImplementation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("request_id", models.UUIDField()),
                ("actor", models.CharField(max_length=100)),
                ("revision", models.PositiveIntegerField()),
                ("specification", models.JSONField()),
                ("expires_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("data", models.JSONField(default=dict)),
                ("payload_bytes", models.PositiveIntegerField(default=0)),
                (
                    "change_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="implementations",
                        to="hubapp.changerequest",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hubapp.organization"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "request_id"),
                        name="request_implementation_identity",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "running")),
                        fields=("change_request",),
                        name="one_running_request_implementation",
                    ),
                ],
            },
        ),
        migrations.RunPython(install_guards, uninstall_guards),
    ]
