# Generated by Django 5.2.17 on 2026-09-24 13:18

import uuid

import django.db.models.deletion
from django.db import migrations, models

TABLES = {
    "projectrelationship": [("source_id", "repository"), ("target_id", "repository")],
    "requesthandoff": [
        ("source_request_id", "changerequest"),
        ("target_id", "repository"),
        ("downstream_request_id", "changerequest"),
    ],
}


def install_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for table, references in TABLES.items():
        name = "hubapp_" + table
        schema_editor.execute(f"ALTER TABLE {name} ENABLE ROW LEVEL SECURITY")
        schema_editor.execute(f"ALTER TABLE {name} FORCE ROW LEVEL SECURITY")
        schema_editor.execute(
            f"CREATE POLICY tenant_isolation ON {name} USING (organization_id = NULLIF(current_setting('hub.organization_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('hub.organization_id', true), '')::uuid)"
        )
        schema_editor.execute(
            f"CREATE TRIGGER tenant_owner_guard BEFORE UPDATE ON {name} FOR EACH ROW EXECUTE FUNCTION hub_check_tenant_reference()"
        )
        for index, (field, related) in enumerate(references):
            schema_editor.execute(
                f"CREATE TRIGGER tenant_reference_{index} BEFORE INSERT OR UPDATE ON {name} FOR EACH ROW EXECUTE FUNCTION hub_check_tenant_reference('{field}', 'hubapp_{related}')"
            )


def uninstall_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for table, references in TABLES.items():
        name = "hubapp_" + table
        for index, _ in enumerate(references):
            schema_editor.execute(f"DROP TRIGGER tenant_reference_{index} ON {name}")
        schema_editor.execute(f"DROP TRIGGER tenant_owner_guard ON {name}")
        schema_editor.execute(f"DROP POLICY tenant_isolation ON {name}")
        schema_editor.execute(f"ALTER TABLE {name} DISABLE ROW LEVEL SECURITY")


class Migration(migrations.Migration):
    dependencies = [
        ("hubapp", "0010_request_implementation"),
    ]

    operations = [
        migrations.AddField(
            model_name="changerequest",
            name="closed_by",
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="changerequest",
            name="closed_from_revision",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="changerequest",
            name="handoff",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="changerequestactivity",
            name="handoff",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="ProjectRelationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.CharField(max_length=1000)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hubapp.organization"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumers",
                        to="hubapp.repository",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="producers",
                        to="hubapp.repository",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "target"), name="project_relationship_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("source", models.F("target")), _negated=True),
                        name="project_relationship_not_self",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RequestHandoff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_by", models.CharField(max_length=254)),
                ("snapshot", models.JSONField()),
                ("payload_bytes", models.PositiveIntegerField(default=0)),
                (
                    "downstream_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_handoff",
                        to="hubapp.changerequest",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hubapp.organization"
                    ),
                ),
                (
                    "source_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_handoffs",
                        to="hubapp.changerequest",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hubapp.repository"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_request", "target"), name="request_handoff_target_unique"
                    )
                ],
            },
        ),
        migrations.RunPython(install_guards, uninstall_guards),
    ]
